#!/usr/bin/perl -w
# chkdups - look for duplicate mibs files.

my $file = shift || 'mib_index.txt';
die "Usage: $0 mib_index.txt\n" unless -r $file;

open (FILE,"<$file") or die "can't open file : $file. $!\n";

while (<FILE>){
    chomp;
    if ($_ =~ /^(.*)\s+(.*)$/){
        my $mib = $1; my $file = $2;
        push @{$MIBS{$mib}},$file;
    }
}

foreach my $mib (keys %MIBS){
    next unless scalar(@{$MIBS{$mib}} > 1);
    print "Duplicate $mib seen in : ",
        join(',',@{$MIBS{$mib}}), "\n";
}
