#!/bin/sh
# mkindex - Makes index of MIBS
# $Id$
FILE=mib_index.txt

echo "Creating $FILE"

echo "MIB Index" > $FILE

# refresh index files
for d in `find -L . -mindepth 1 -type d -not -name CVS | grep -v .git`; do
    snmptranslate -M$d sysName > /dev/null 2>&1
done

# Add contents of each .index to our index
for f in `find -L . -name .index`; do
    echo "" >> $FILE
    echo $f >> $FILE
    cat $f | sort -i >> $FILE
    echo "" >> $FILE
done
