--**MOD+***********************************************************************
--* Module:    ARUBAWIRED-NETWORKING-OID.mib
--*
--* (c) Copyright 2017-2018 Hewlett Packard Enterprise Development LP
--* All Rights Reserved.
--*
--* The contents of this software are proprietary and confidential
--* to the Hewlett-Packard Development Company, L.P.  No part of this
--* program may be photocopied, reproduced, or translated into another
--* programming language without prior written consent of the
--* Hewlett-Packard Development Company, L.P.
--*
--* Purpose: This file contains MIB definition of ARUBAWIRED-NETWORKING-OID
--*
--**MOD-***********************************************************************

ARUBAWIRED-NETWORKING-OID DEFINITIONS ::= BEGIN

IMPORTS
        enterprises, MODULE-IDENTITY, OBJECT-IDENTITY
            FROM SNMPv2-SMI;

hpeNetworking MODULE-IDENTITY
         LAST-UPDATED "201810100000Z"  -- Oct 10, 2018

         ORGANIZATION "HPE/Aruba Networking Division"
         CONTACT-INFO "Hewlett Packard Company
                       8000 Foothills Blvd.
                       Roseville, CA 95747"

         DESCRIPTION  "This MIB module defines HPE Networking
                       product hardware MIBs and proprietary MIBs. "

         REVISION     "201810100000Z"  -- Oct 10, 2018
         DESCRIPTION  "Added new 8325 switches and updated description
                       text for all 8325 switches"

         REVISION     "201804120000Z"  -- Apr 12, 2018
         DESCRIPTION  "Made changes to move VSX MIB under new OID tree."

         REVISION     "201804090000Z"  -- Apr 09, 2018
         DESCRIPTION  "Added new 8320 switches and updated description
                       text for all 8320 switches"

         REVISION     "201711280000Z"  -- Nov 28, 2017
         DESCRIPTION  "Added port vendor types"

         REVISION     "201711140000Z"  -- Nov 14, 2017
         DESCRIPTION  "Added RPM and Power sensors"

         REVISION     "201711020000Z"  -- Nov 2, 2017
         DESCRIPTION  "Added 8400 Rear Display Module"

         REVISION     "201710240000Z"  -- Oct 24, 2017
         DESCRIPTION  "Updated Aruba Wired MIB Object Names with a
                       standard convention"

         REVISION     "201708300000Z"  -- Aug 30, 2017
         DESCRIPTION  "Updated with 8320 switch information"

         REVISION     "201704110000Z"  -- Apr 11, 2017
         DESCRIPTION  "Updated with 8400 SKU information"

         ::= { hpe 4 }

hpe    OBJECT IDENTIFIER ::= { enterprises  47196 }

-- definition of HPENetworking Objects
-- reserving object with zero
reservedhpeNetworking OBJECT IDENTIFIER ::=  { hpeNetworking 0 }

-- grouping all wired devices under a separate group
wiredNetworkingDevices OBJECT IDENTIFIER ::= { hpeNetworking 1 }

-- categorization of MIB portions
arubaOS-CX OBJECT IDENTIFIER ::= { wiredNetworkingDevices 1 }

wndDeviceIds OBJECT IDENTIFIER ::= { arubaOS-CX 1 }

wndComponentIds OBJECT IDENTIFIER ::= { arubaOS-CX 2 }

wndFeatures OBJECT IDENTIFIER ::= { arubaOS-CX 3 }

-- detailing of products

arubaWiredSwitchJL375A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL375A Aruba 8400 8-slot chassis switch."
        ::= { wndDeviceIds 1 }

arubaWiredSwitchJL479A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL479A Aruba 8320 48p 10G SFP/SFP+ and 6p 40G QSFP+ chassis switch."
        ::= { wndDeviceIds 2 }

arubaWiredSwitchJL579A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL579A Aruba 8320 32p QSFP+ chassis switch."
        ::= { wndDeviceIds 3 }

arubaWiredSwitchJL581A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL581A Aruba 8320 48p 1G/10GBASE-T and 6p 40G QSFP+ chassis switch."
        ::= { wndDeviceIds 5 }

arubaWiredSwitchJL635A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL635A Aruba 8325 8325-48Y8C chassis switch."
        ::= { wndDeviceIds 50 }

arubaWiredSwitchJL636A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for the
                     JL636A Aruba 8325 8325-32C chassis switch."
        ::= { wndDeviceIds 70 }

-- sensors are sub type of parts

wndSensors  OBJECT IDENTIFIER ::= { wndComponentIds 1 }

wndTemperatureSensor OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Identifier for a temperature sensor type."
        ::= { wndSensors 1 }

wndRPMSensor OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Identifier for a fan RPM sensor type."
        ::= { wndSensors 2 }

wndPowerSensor OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Identifier for a PSU power sensor type."
        ::= { wndSensors 3 }

-- slots are sub-type of parts

wndSlots  OBJECT IDENTIFIER ::= { wndComponentIds 2 }

arubaWiredSwitch8400FanTraySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Represents slot for Aruba X731 Fan Tray. "
        ::= { wndSlots 1 }

arubaWiredSwitch8400PowerSupplySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a
                    power supply bay in an Aruba 8400 switch
                    chassis. "
        ::= { wndSlots 2 }

arubaWiredSwitch8400ManagementModuleSlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a
                    Management Module bay in a Aruba 8400 switch. "
        ::= { wndSlots 3 }

arubaWiredSwitch8400LineCardSlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a line card
                    module slot in an Aruba 8400 switch chassis. "
        ::= { wndSlots 4 }

arubaWiredSwitch8400FabricCardSlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a fabric
                    module slot in an Aruba 8400 switch chassis. "
        ::= { wndSlots 5 }

arubaWiredSwitch8400RearDisplayCardSlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a fabric
                    module slot in an Aruba 8400 switch chassis. "
        ::= { wndSlots 6 }

arubaWiredSwitch8320FanTraySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Represents slot for Aruba F2B Fan Tray. "
        ::= { wndSlots 7 }

arubaWiredSwitch8320PowerSupplySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a
                    power supply bay in an Aruba 8320 switch
                    chassis. "
        ::= { wndSlots 8 }

arubaWiredSwitch8325FanTraySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "Represents slot for Aruba Fan Tray. "
        ::= { wndSlots 9 }

arubaWiredSwitch8325PowerSupplySlot OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a
                    power supply bay in an Aruba 8325 switch
                    chassis. "
        ::= { wndSlots 10 }

-- modules are sub types of parts

wndModules  OBJECT IDENTIFIER ::= { wndComponentIds 3 }

arubaWiredSwitchManagementModuleJL368A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400 Management Module. "
        ::= { wndModules 1 }

arubaWiredSwitchModuleJL363A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400X 32-port 10GbE SFP/SFP+ with MACsec Advanced Module. "
        ::= { wndModules 2 }

arubaWiredSwitchModuleJL365A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400X 8-port 40GbE QSFP+ Advanced Module."
        ::= { wndModules 3 }

arubaWiredSwitchModuleJL366A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400X 6-port 40GbE/100GbE QSFP28 Advanced Module. "
        ::= { wndModules 4 }

arubaWiredSwitchFabricModuleJL367A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400X 7.2Tbps Fabric Module. "
        ::= { wndModules 5 }

arubaWiredSwitchFanModuleJL370A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400 Fan for X731 Fan Tray. "
        ::= { wndModules 6 }

arubaWiredSwitchPowerSupplyUnitJL372A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba X382 54VDC 2700W AC Power Supply. "
        ::= { wndModules 7 }

arubaWiredSwitchJL369AFanTray OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba X731 Fan Tray. "
        ::= { wndModules 8 }

arubaWiredSwitchModuleJL479A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8320 48p 10G SFP/SFP+ and 6p 40G QSFP+ Advanced Module."
        ::= { wndModules 9 }

arubaWiredSwitchPowerSupplyUnitJL480A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8320 400W AC Power Supply. "
        ::= { wndModules 10 }

arubaWiredSwitchJL481AFanTray OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8320 Fan Tray. "
        ::= { wndModules 11 }

arubaWiredSwitchRearDisplayModule8400 OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8400 Rear Display Module. "
        ::= { wndModules 12 }

arubaWiredSwitch1GbMaxPort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a 1Gb maximum speed port."
        ::= { wndModules 13 }

arubaWiredSwitch10GbMaxPort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a 10Gb maximum speed port."
        ::= { wndModules 14 }

arubaWiredSwitch25GbMaxPort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a 25Gb maximum speed port."
        ::= { wndModules 15 }

arubaWiredSwitch40GbMaxPort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a 40Gb maximum speed port."
        ::= { wndModules 16 }

arubaWiredSwitch100GbMaxPort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a 100Gb maximum speed port."
        ::= { wndModules 17 }

arubaWiredSwitchSmartRatePort OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for a Smart Rate multi-gigabit port."
        ::= { wndModules 18 }

arubaWiredSwitchModuleJL579A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8320 32p 40GbE QSFP+ Advanced Module."
        ::= { wndModules 19 }

arubaWiredSwitchModuleJL581A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8320 48p 1G/10GBASE-T and 6p 40G QSFP+ Advanced Module."
        ::= { wndModules 20 }

arubaWiredSwitchModuleJL635A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-48Y8C Module."
        ::= { wndModules 21 }

arubaWiredSwitchModuleJL624A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-48Y8C FB Module."
        ::= { wndModules 22 }

arubaWiredSwitchModuleJL625A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-48Y8C BF Module."
        ::= { wndModules 23 }

arubaWiredSwitchModuleJL636A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-32C Module."
        ::= { wndModules 24 }

arubaWiredSwitchModuleJL626A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-32C FB Module."
        ::= { wndModules 25 }

arubaWiredSwitchModuleJL627A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-32C BF Module."
        ::= { wndModules 26 }

arubaWiredSwitchPowerSupplyUnitJL632A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325 650W 100-240V FB AC Power Supply. "
        ::= { wndModules 27 }

arubaWiredSwitchPowerSupplyUnitJL633A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325 650W 100-240V BF AC Power Supply. "
        ::= { wndModules 28 }

arubaWiredSwitchFanTrayJL628A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-48Y8C F2B Fan Tray. "
        ::= { wndModules 29 }

arubaWiredSwitchFanTrayJL629A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-48Y8C B2F Fan Tray. "
        ::= { wndModules 30 }

arubaWiredSwitchFanTrayJL630A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-32C F2B Fan Tray. "
        ::= { wndModules 31 }

arubaWiredSwitchFanTrayJL631A OBJECT-IDENTITY
        STATUS      current
        DESCRIPTION "The authoritative identifier for Aruba 8325-32C B2F Fan Tray. "
        ::= { wndModules 32 }

-- Feature Sub-tree where we allocate OID for Proprietary MIBs

arubaWiredLoopProtectMIB     OBJECT IDENTIFIER ::= { wndFeatures 1 }

arubaWiredMclagMIB           OBJECT IDENTIFIER ::= { wndFeatures 2 }

arubaWiredMgmdSnoopingMIB    OBJECT IDENTIFIER ::= { wndFeatures 3 }

arubaWiredMgmdRmonTrapMIB    OBJECT IDENTIFIER ::= { wndFeatures 4 }

arubaWiredRpvstMIB           OBJECT IDENTIFIER ::= { wndFeatures 5 }

arubaWiredMvrpMIB            OBJECT IDENTIFIER ::= { wndFeatures 6 }

arubaWiredVsxMIB             OBJECT IDENTIFIER ::= { wndFeatures 7 }

END
