#!/usr/bin/env perl
# setmaxtc - build and use net-snmp with 16k MAXTC

# On a scale of 1 to wrong this is 11. I blame jeneric ;-).

use strict;
use warnings;
use File::Path;

if (!defined $ENV{MIBHOME}) {
  print "error: must define \$MIBHOME (where the MIB dirs live)\n";
  exit(1);
}

my $home = "$ENV{MIBHOME}/extras/net-snmp.local";
my $localenv = "$home/bin/localenv perl";

if (not (-e $localenv and -x $localenv)) {
  File::Path::remove_tree($home);
  mkdir $home;

  # FIXME: seems not to install dylibs on MacOS? (but manual install does)
  system(qq{curl -L https://cpanmin.us/ | perl - --quiet --notest --local-lib $home }
    . q{App::cpanminus App::local::lib::helper PkgConfig }
    . q{git@github.com:ollyg/Alien-SNMP-MAXTC.git}) and die ($? >> 8);
}

my $bindir = qx($home/bin/localenv perl -MAlien::SNMP::MAXTC -e 'print Alien::SNMP::MAXTC->bin_dir');
exec(qq{$home/bin/localenv bash -c 'export PATH="$bindir:\$PATH";\$SHELL'});
