#!/usr/bin/env perl
# compare new_mib_file
# will run a diff against the version of the same MIB in netdisco-mibs

use strict;
use warnings;

use File::Temp;
use File::Basename;
use File::Spec::Functions qw(splitdir catfile);

use FindBin;
use lib catfile($FindBin::Bin, 'lib');
use Helpers;

my $newmib = shift;
if (!defined $newmib or not -f $newmib) {
  print "usage: $0 new_mib_file\n";
  exit(1);
}

# make an index so that net-snmp tells us what MIB is in the file
my ($mibs_for, $files_for) = build_index($newmib);

if ((scalar keys %$files_for) == 0) {
  print "error: unable to parse MIB DEFINITIONS in $newmib\n";
  exit(1);
}

my $mib = (keys %$files_for)[0];
my ($file_mibs, $mib_vendors, $mib_files, $vendor_files) = mkindex();

if (!exists $mib_vendors->{$mib} or !exists $mib_files->{$mib}) {
  print "error: MIB $mib is unknown to netdisco-mibs\n";
  exit(1);
}

# run a diff
my $oldmib = catfile($ENV{MIBHOME}, $mib_files->{$mib}->[0]);
exec(qq{diff -b -B -w --strip-trailing-cr '$oldmib' '$newmib' | less});
