#!/usr/bin/env perl
# compare new_mib_file
# will run a diff against the version of the same MIB in netdisco-mibs

use strict;
use warnings;

use charnames ':full';
binmode STDOUT, ':utf8';

use File::Basename;
use File::Spec::Functions qw(splitdir catfile);
use Term::ANSIColor qw(:constants);

if (!defined $ENV{MIBHOME}) {
  print "error: must define \$MIBHOME (where the MIB dirs live)\n";
  exit(1);
}

$ENV{SNMP_PERSISTENT_DIR} = "$ENV{MIBHOME}/extras/indexes";

my $newmib = shift;
my $newdir = (fileparse((fileparse($newmib))[1]))[1];
if (!defined $newmib or not -f $newmib) {
  print "usage: $0 new_mib_file\n";
  exit(1);
}

my $vendor = (grep {m/\S/} splitdir($newmib))[-2];
my $olddir = catfile($ENV{MIBHOME}, $vendor);
if (! -d $olddir) {
  print "error: no directory in MIBHOME named $vendor\n";
  exit(1);
}

# find the MIB name
my $newidx = catfile($newdir, 'ignore', 'dotindex.txt');
if (! -f $newidx) {
  print "error: no MIB index found at $newidx\n";
  exit(1);
}

# find the file in old_dir with the same MIB

# run a diff


__END__
if (scalar grep {-f} glob(catfile($from, 'error', '*'))) {
  print "error: prepmibs found some errors you need to address.\n";
  exit(1);
}

print "\N{HEAVY CHECK MARK} Imported MIBs.\n";
exit(0);
