#!/usr/bin/env perl
# mkindex - restores a portable index cache to the live indexes

use strict;
use warnings;

use charnames ':full';
binmode STDOUT, ':utf8';

use File::Find;
use File::Copy;
use Term::ANSIColor qw(:constants);

if (!defined $ENV{MIBHOME}) {
  print "error: must define \$MIBHOME (where the MIB dirs live)\n";
  exit(1);
}

$ENV{SNMPCONFPATH} = '';
$ENV{SNMP_PERSISTENT_DIR} = "$ENV{MIBHOME}/extras/indexes";
$ENV{MIBS} = 'SNMPv2-MIB';
$ENV{MIBDIRS} = "$ENV{MIBHOME}/net-snmp:$ENV{MIBHOME}/rfc:$ENV{MIBHOME}/cisco";

# first setup
mkdir "$ENV{SNMP_PERSISTENT_DIR}/mib_indexes";
mkdir "$ENV{SNMP_PERSISTENT_DIR}/cache";

# clean out any live indexes
find(sub{ -d or unlink or die $! },
  "$ENV{SNMP_PERSISTENT_DIR}/mib_indexes");

# run mkcache always
system(catfile($FindBin::Bin, 'mkcache')) and exit ($? >> 8);

open(my $mibindex2, '>', "$ENV{SNMP_PERSISTENT_DIR}/mib_index2.txt") or die $!;
print $mibindex2 "MIB Index v2\n";
my $idxcount = 0;

find(sub{
  return if -d;
  my $dest = "$ENV{SNMP_PERSISTENT_DIR}/mib_indexes/$idxcount";

  open(my $src, '<', $File::Find::name) or die $!;
  open(my $newindex, '>', $dest) or die $!;

  print $mibindex2 "\n";
  print $mibindex2 "DIR $ENV{MIBHOME}/$_\n";
  print $newindex  "DIR $ENV{MIBHOME}/$_\n";

  while (my $line = <$src>) {
    print $mibindex2 $line;
    print $newindex  $line;
  }

  close $newindex;
  close $src;
  ++$idxcount;
}, "$ENV{SNMP_PERSISTENT_DIR}/cache");

close $mibindex2;

print "\N{HEAVY CHECK MARK} Indexes rebuilt.\n";
exit(0);
