#!/usr/bin/env perl
# setmaxtc - build and use net-snmp with 16k MAXTC
# I blame (& owe credit to) jeneric ;-).

use strict;
use warnings;
use File::Path;

if (!defined $ENV{MIBHOME}) {
  print "error: must define \$MIBHOME (where the MIB dirs live)\n";
  exit(1);
}

my $home = "$ENV{MIBHOME}/extras/net-snmp.local";
my $localenv = "$home/bin/localenv";

if (not (-e $localenv and -x $localenv)) {
  File::Path::remove_tree($home);
  mkdir $home;

  system(qq{curl -sL https://cpanmin.us/ | perl - --quiet --notest --local-lib $home}
    . q{ App::cpanminus App::local::lib::helper PkgConfig }
    . q{ git@github.com:ollyg/Alien-SNMP-MAXTC.git }) and die ($? >> 8);
}

my $bindir = qx($localenv perl -MAlien::SNMP::MAXTC -e 'print Alien::SNMP::MAXTC->bin_dir');
exec(qq{$localenv $ENV{SHELL} -c 'export PATH="$bindir:\$PATH";\$SHELL'});
