#!/bin/sh
# walk_all
#   takes same syntax as snmpwalkmib, but finds all the mibs for you.

if [ "$1" = "" ]; then
    echo "walk_all - run snmpwalkmib on all mibs."
    echo "           Pass same arguments as snmpwalkmib, except don't specify the mib."
    echo ""
    ./snmpwalkmib -h
    exit
fi

for f in `cat mib_index.txt | cut -f 1 -d ' ' | grep -v .index` ; do
    ./snmpwalkmib $* $f
done
