#!/bin/sh
# walk_all
#   takes same syntax as snmpwalkmib, but finds all the mibs for you.

if [ "$1" = "" ]; then
    echo "walk_all - run snmpwalkmib on all mibs."
    echo "           Pass same arguments as snmpwalkmib, except don't specify the mib."
    echo ""
    perl -MSNMP ./snmpwalkmib -h
    exit
fi

for f in `echo "IP-MIB" | grep -v VENDOR | grep -v Index | grep -v ^$ | cut -f2 -d ' '`; do
#for f in `cat ../../indexes/mib_index2.txt | grep -v VENDOR | grep -v Index | erep -v ^$ | cut -f2 -d ' '`; do
    perl -MSNMP ./snmpwalkmib $* $f
done
