HP-ICF-DHCPCLIENT-MIB DEFINITIONS ::= BEGIN

    IMPORTS
        hpSwitch            
            FROM HP-ICF-OID            
        OBJECT-TYPE, MODULE-IDENTITY
            FROM SNMPv2-SMI
        MODULE-COMPLIANCE, OBJECT-GROUP
            FROM SNMPv2-CONF;

    -- 1.3.6.1.4.1.11.2.14.11.5.1.57
    hpicfDhcpClient MODULE-IDENTITY 
        LAST-UPDATED "200903180000Z" -- March 18, 2009 at 00:00 GMT
        ORGANIZATION 
            "Hewlett-Packard Company
            Procurve Networking Business"
        CONTACT-INFO 
            "Hewlett-Packard Company
            8000 Foothills Blvd.
            Roseville, CA 95747"
        DESCRIPTION 
            "This MIB module contains HP proprietary
            objects for managing DHCP Client."

        REVISION "200903180000Z"      -- March 18, 2009 at 00:00 GMT
        DESCRIPTION
            "Added 'hpicfDhcpClientImageFileUpdate' MIB object"

        REVISION "200810300000Z"      -- October 30, 2008 at 00:00 GMT
        DESCRIPTION 
            "Added 'hpicfDhcpClientHostNameOption' MIB object"
	    
        REVISION "200808270038Z"      -- August 27, 2008 at 00:38 GMT
        DESCRIPTION 
            "Initial revision."
        ::= { hpSwitch 57 }

--
-- Node definitions
--

      -- 1.3.6.1.4.1.11.2.14.11.5.1.57.1
     hpicfDhcpClientOptions OBJECT IDENTIFIER ::= { hpicfDhcpClient 1 }

      -- 1.3.6.1.4.1.11.2.14.11.5.1.57.2
     hpicfDhcpClientOptionsConf OBJECT IDENTIFIER ::= { hpicfDhcpClient 2 }

      -- 1.3.6.1.4.1.11.2.14.11.5.1.57.1.1
     hpicfDhcpClientVendorSpecOptionStatus OBJECT-TYPE
         SYNTAX      INTEGER{
                             enable(1),
                             disable(2)
                    }
         MAX-ACCESS  read-write
         STATUS      current
         DESCRIPTION "This flag indicates whether DHCP vendor specific
                      configurations are enabled for this interface or not.
                      
                      Setting this flag to 'enabled' (the default) results
                      in sending 'Vendor Class Identifier' (VCI) to DHCP server
                      and requesting vendor specific configurations from DHCP
                      servers for this interface. Refer RFC 2132 for more
                      details.
                      
                      Setting this flag to 'disabled' results in not sending
                      VCI to DHCP server and not requesting vendor specific
                      configurations from DHCP servers."
         ::= { hpicfDhcpClientOptions 1 }


      -- 1.3.6.1.4.1.11.2.14.11.5.1.57.1.2
     hpicfDhcpClientHostNameOption OBJECT-TYPE
         SYNTAX      INTEGER{
                             enable(1),
                             disable(2)
                    }
         MAX-ACCESS  read-write
         STATUS      current
         DESCRIPTION "This object enables/disabled DHCP option 12 that
                      allows for sending system hostname in DHCP packets.

		      By default this object is set to be disabled.
                      
                      Setting this flag to 'enabled' results in the 
                      inclusion of system hostname in DHCP packets."
         ::= { hpicfDhcpClientOptions 2 }
     
      -- 1.3.6.1.4.1.11.2.14.11.5.1.57.1.3
     hpicfDhcpClientImageFileUpdate OBJECT-TYPE
		
         SYNTAX       INTEGER{
                             enabled(1),
                             disabled(2)
                     }
         MAX-ACCESS  read-write
         STATUS      current
         DESCRIPTION "This object facilitates enabling or disabling of
                      the image file update feature through DHCP. 
                      Setting this object to 1 enables this feature
                      and setting it to 2 disables this feature.
                      This MIB object can be set to 1 only if 
                      hpicfDhcpClientVendorSpecOptionStatus has already
                      been set to 1. 
                      By default, hpicfDhcpClientImageFileUpdate is set
                      to 1. When this feature is enabled, the Auto-TFTP
                      settings will be disabled."
         ::= { hpicfDhcpClientOptions 3 }

------------------------------------------------------------------------------
-- Conformance Information
------------------------------------------------------------------------------

    hpicfDhcpClientGroups        
    OBJECT IDENTIFIER ::= { hpicfDhcpClientOptionsConf 1 }
    hpicfDhcpClientCompliances   
    OBJECT IDENTIFIER ::= { hpicfDhcpClientOptionsConf 2 }

-- compliance statements

    hpicfDhcpClientCompliance MODULE-COMPLIANCE
        STATUS          current
        DESCRIPTION     "The compliance statement for DHCP Client implementation."
        MODULE          -- this module
        MANDATORY-GROUPS { hpicfDhcpClientOptionsGroup }
    ::= { hpicfDhcpClientCompliances 1 }

    hpicfDhcpClientVendorSpecOptionsCompliance MODULE-COMPLIANCE
        STATUS          current
        DESCRIPTION     "The compliance statement for DHCP client implementation."
        MODULE          -- this module
        MANDATORY-GROUPS { hpicfDhcpClientVendorSpecOptionsGroup }
    ::= { hpicfDhcpClientCompliances 2 }

-- MIB Groupings

    hpicfDhcpClientOptionsGroup OBJECT-GROUP
    OBJECTS {
      hpicfDhcpClientVendorSpecOptionStatus,
      hpicfDhcpClientHostNameOption
    }
    STATUS              current
    DESCRIPTION         "A mandatory group with a set of DHCP client's option 
                         object(s)."
    ::= { hpicfDhcpClientGroups 1 }

    hpicfDhcpClientVendorSpecOptionsGroup OBJECT-GROUP
    OBJECTS {
      hpicfDhcpClientImageFileUpdate
    }
    STATUS              current
    DESCRIPTION         "A mandatory group with a set of DHCP vendor
                         specific option object(s)."
    ::= { hpicfDhcpClientGroups 2 } 

END
