name: GitHub Release on Tag
on:

  workflow_dispatch:
    inputs:
      netdisco_mibs_tag:
        description: 'netdisco-mibs tag to use'
        required: false
        type: string
        default: ''
      debug:
        description: 'With debug'
        required: false
        default:  'false'

  push:
    branches:
      - master
    tags:
      - '4.[0-9][0-9][0-9]'

jobs:
  release_netdisco_mibs:
    if: |
      github.event_name == 'workflow_dispatch'
      || (github.event_name != 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Get the Tag
        run: |
          echo "GH_REF_SHORT=${{ inputs.netdisco_mibs_tag || github.ref_name }}" >> $GITHUB_ENV

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v3.0.2
        with:
          name: netdisco-mibs-${{ env.GH_REF_SHORT }}
          tag_name: ${{ env.GH_REF_SHORT }}

      - name: Download tarball
        run: |
          curl -LO https://github.com/netdisco/netdisco-mibs/archive/refs/tags/${{ env.GH_REF_SHORT }}.tar.gz

      - name: Fetch files from external repository, add to archive, rename
        run: |
          tar -zxvf ${{ env.GH_REF_SHORT }}.tar.gz
          cd netdisco-mibs-${{ env.GH_REF_SHORT }}
          mkdir -p EXTRAS/sql
          curl -L -o EXTRAS/sql/snmp-info-snmp-filter.sql "https://github.com/netdisco/upstream-sources/raw/refs/heads/master/bootstrap/snmp-info-snmp-filter.sql"
          curl -L -o EXTRAS/sql/netdisco-mibs-snmp-object.sql.gz "https://github.com/netdisco/upstream-sources/raw/refs/heads/master/bootstrap/netdisco-mibs-snmp-object.sql.gz"
          cd ..
          tar -czf netdisco-mibs.tar.gz -C netdisco-mibs-${{ env.GH_REF_SHORT }} --transform 's,^,netdisco-mibs-${{ env.GH_REF_SHORT }}/,' .

      - name: Get upload URL
        run: |
          echo UPLOAD_URL=${{ steps.create_release.outputs.upload_url }} | cut -d ' ' -f 1 >> $GITHUB_ENV

      - name: Upload tarball
        id: upload_tarball_after_release
        run: |
          curl \
            -f \
            -sSL \
            -XPOST \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -H 'Content-Type: application/gzip' \
            --upload-file 'netdisco-mibs.tar.gz' \
            '${{ env.UPLOAD_URL }}=netdisco-mibs.tar.gz'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.24
        if: always() && github.event.inputs.debug == 'true'
        with:
          sudo: true
